// <auto-generated />
namespace bi130168d.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bi130168 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bi130168));
        
        string IMigrationMetadata.Id
        {
            get { return "201609250029199_bi130168"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
